### ISSUE TITLE
Pre-migration checklist

### ISSUE THREAD

**Issue by rayroman** [gronda-team/signature-ui-sandbox#4]
Here are some summarized to-dos to be completed before the repository is ready to be used in the web app.

- [x] Adding new theme colors + exports
- [x] Exporting theme generator to create new consumer-side themes (including font family, font sizes, etc.)
- [ ] Exporting CDK elements (`ListKeyManager`, `SelectionManager`, `FocusMonitor`, among others) so they can be used on the client-side
- [ ] Replacing `aria-invalid={false}` with `aria-invalid={this.props.invalid}` (client-side management of error states is recommended for now because a repository-level `Form` element with form checking is infeasible prior to release.)
